In [1]:
import pandas as pd
import json
from pathlib import Path

In [2]:
import sys
print(sys.executable)

/home/datalab/projects/data-engineer-coding-interview/challenge1/.venv/bin/python

In [ ]:
DATA_DIR = Path("/home/datalab/projects/YipitData-take-home-exercise")

TECH_NEWS_FILE = DATA_DIR / "tech_news.csv"
COMPANY_METADATA_FILE = DATA_DIR / "company_metadata.json"

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
articles_df = pd.read_csv(TECH_NEWS_FILE,dtype=str)

articles_df.head()

,article_id,title,company_name,published_date,category,revenue,summary,url,author,word_count
0,ART0001,Scale AI Raises Series D Funding Round,Scale AI,21 Feb 2020,Financial Technology,NaN,The company demonstrated significant advances ...,https://technews.example.com/articles/1,John Smith,2569.0
1,ART0002,DataRobot Announces Breakthrough in Large Lang...,DataRobot,02/23/2023,Software,"£244,094,488",Strategic acquisition strengthens competitive ...,https://technews.example.com/articles/2,Alex Johnson,1878.0
2,ART0003,Meta AI Raises Series D Funding Round,Meta AI,2022-02-17,Analytics,NaN,Leadership outlines vision for responsible AI ...,https://technews.example.com/articles/3,John Smith,1981.0
3,ART0004,Confluent Reports Record Revenue Growth,Confluent,2023-12-13,Artificial Intelligence,$980.0M,Investors show strong confidence in the compan...,https://technews.example.com/articles/4,Sam Wilson,1994.0
4,ART0005,Amazon Web Services Acquires Competitor for Un...,Amazon Web Services,12/28/2021,Financial Technology,Not disclosed,Leadership outlines vision for responsible AI ...,https://technews.example.com/articles/5,Alex Johnson,2781.0

In [10]:
articles_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   article_id      750 non-null    str
 1   title           750 non-null    str
 2   company_name    750 non-null    str
 3   published_date  750 non-null    str
 4   category        750 non-null    str
 5   revenue         643 non-null    str
 6   summary         750 non-null    str
 7   url             750 non-null    str
 8   author          546 non-null    str
 9   word_count      681 non-null    str
dtypes: str(10)
memory usage: 58.7 KB

In [12]:
articles_df.isna().sum()

article_id          0
title               0
company_name        0
published_date      0
category            0
revenue           107
summary             0
url                 0
author            204
word_count         69
dtype: int64

In [13]:
articles_df.sample(10)

,article_id,title,company_name,published_date,category,revenue,summary,url,author,word_count
690,ART0691,Mistral AI Raises Series D Funding Round,Mistral AI,2024-12-13T00:00:00Z,AI & ML,$260.0M,Investors show strong confidence in the compan...,https://technews.example.com/articles/691,Alex Johnson,2411.0
315,ART0316,Meta AI Reports Record Revenue Growth,Meta AI,06 Jan 2023,Cybersecurity,"$1,200,000,000",Major partnership validates technology and ope...,https://technews.example.com/articles/316,NaN,858.0
394,ART0395,Google DeepMind Partners with Major Enterprise...,Google DeepMind,16 Mar 2023,Artificial Intelligence,NaN,Platform improvements deliver enhanced perform...,https://technews.example.com/articles/395,Jane Doe,2469.0
97,ART0098,Amazon Web Services Acquires Competitor for Un...,Amazon Web Services,30 Sep 2021,Data Analytics,Not disclosed,The company demonstrated significant advances ...,https://technews.example.com/articles/98,NaN,NaN
2,ART0003,Meta AI Raises Series D Funding Round,Meta AI,2022-02-17,Analytics,NaN,Leadership outlines vision for responsible AI ...,https://technews.example.com/articles/3,John Smith,1981.0
42,ART0043,Uber Acquires Competitor for Undisclosed Sum,Uber,"March 09, 2021",Data Analytics,Not disclosed,International expansion strategy focuses on en...,https://technews.example.com/articles/43,John Smith,2709.0
745,ART0746,Stripe Inc. Acquires Competitor for Undisclose...,Stripe Inc.,"December 02, 2024",SaaS,"£3,078,740,157",New product features leverage cutting-edge AI ...,https://technews.example.com/articles/746,John Smith,2891.0
332,ART0333,Scale AI Expands into European Market,Scale AI,03/09/2021,Cloud,"£165,354,331",Strategic acquisition strengthens competitive ...,https://technews.example.com/articles/333,NaN,2461.0
107,ART0108,Palantir Faces Regulatory Scrutiny,Palantir,08/27/2023,Data Analytics,"¥315,000,000,000",Investors show strong confidence in the compan...,https://technews.example.com/articles/108,Alex Johnson,845.0
311,ART0312,MongoDB Raises Series D Funding Round,MongoDB,10/31/2022,Cybersecurity,$1.380B,Financial results exceed analyst expectations ...,https://technews.example.com/articles/312,NaN,1977.0

In [ ]:
# https://docs.python.org/uk/3/library/json.html
with open(COMPANY_METADATA_FILE, "r", encoding="utf-8") as file:
    company_metadata = json.load(file)

In [15]:
list(company_metadata.items())[:3]

[('OpenAI',
  {'founded_year': 2006,
   'headquarters': 'Austin, TX',
   'employee_count': 12793,
   'industry': 'Data Analytics',
   'is_public': False,
   'stock_ticker': 'OPEN'}),
 ('Anthropic',
  {'founded_year': 2006,
   'headquarters': 'San Francisco, CA',
   'employee_count': 43747,
   'industry': 'FinTech',
   'is_public': False,
   'stock_ticker': None}),
 ('Google DeepMind',
  {'founded_year': 2017,
   'headquarters': 'Austin, TX',
   'employee_count': 24274,
   'industry': 'Data Analytics',
   'is_public': False,
   'stock_ticker': None})]

In [19]:
# https://pandas.pydata.org/pandas-docs/version/2.3/reference/api/pandas.DataFrame.from_dict.html
companies_df = (
    pd.DataFrame.from_dict(company_metadata, orient="index", dtype=str)
    .reset_index()
    .rename(columns={"index": "company_name"})
)

companies_df.head()

,company_name,founded_year,headquarters,employee_count,industry,is_public,stock_ticker
0,OpenAI,2006,"Austin, TX",12793,Data Analytics,False,OPEN
1,Anthropic,2006,"San Francisco, CA",43747,FinTech,False,NaN
2,Google DeepMind,2017,"Austin, TX",24274,Data Analytics,False,NaN
3,Meta AI,2001,"Seattle, WA",20240,Data Analytics,True,NaN
4,Microsoft,2018,"Austin, TX",48646,Data Analytics,False,NaN

In [20]:
companies_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   company_name    21 non-null     str
 1   founded_year    21 non-null     str
 2   headquarters    21 non-null     str
 3   employee_count  21 non-null     str
 4   industry        21 non-null     str
 5   is_public       21 non-null     str
 6   stock_ticker    7 non-null      str
dtypes: str(7)
memory usage: 1.3 KB

In [21]:
companies_df

,company_name,founded_year,headquarters,employee_count,industry,is_public,stock_ticker
0,OpenAI,2006,"Austin, TX",12793,Data Analytics,False,OPEN
1,Anthropic,2006,"San Francisco, CA",43747,FinTech,False,NaN
2,Google DeepMind,2017,"Austin, TX",24274,Data Analytics,False,NaN
3,Meta AI,2001,"Seattle, WA",20240,Data Analytics,True,NaN
4,Microsoft,2018,"Austin, TX",48646,Data Analytics,False,NaN
5,Amazon Web Services,2015,"Berlin, Germany",27826,SaaS,False,NaN
6,Tesla,2008,"London, UK",5691,Cloud Computing,True,NaN
7,NVIDIA,2017,"London, UK",22031,AI/ML,False,NaN
8,Databricks,2003,"Berlin, Germany",17962,Data Analytics,True,DATA
9,Snowflake,2012,"London, UK",49545,Cloud Computing,True,NaN
10,Stripe,2002,"Seattle, WA",36348,Data Analytics,True,STRI
11,Airbnb,1999,"London, UK",19967,Data Analytics,False,NaN
12,Uber,2015,"San Francisco, CA",10144,FinTech,False,UBER
13,SpaceX,2016,"Berlin, Germany",31018,AI/ML,False,NaN
14,Palantir,2005,"Berlin, Germany",42306,Cloud Computing,True,NaN
15,Cloudflare,1998,"Austin, TX",4422,Cybersecurity,False,CLOU
16,MongoDB,2008,"Austin, TX",16952,SaaS,False,MONG
17,Elastic,2016,"San Francisco, CA",24508,Cybersecurity,True,ELAS
18,Confluent,1995,"London, UK",3884,Cloud Computing,False,NaN
19,DataRobot,2012,"New York, NY",23471,Cloud Computing,True,NaN
20,Scale AI,2003,"Berlin, Germany",23379,AI/ML,False,NaN

In [31]:
articles_df[articles_df["revenue"].isna()]

,article_id,title,company_name,published_date,category,revenue,summary,url,author,word_count
0,ART0001,Scale AI Raises Series D Funding Round,Scale AI,21 Feb 2020,Financial Technology,NaN,The company demonstrated significant advances ...,https://technews.example.com/articles/1,John Smith,2569.0
2,ART0003,Meta AI Raises Series D Funding Round,Meta AI,2022-02-17,Analytics,NaN,Leadership outlines vision for responsible AI ...,https://technews.example.com/articles/3,John Smith,1981.0
7,ART0008,Microsoft Releases Open Source Framework,Microsoft,2022-10-07,Artificial Intelligence,NaN,Leadership outlines vision for responsible AI ...,https://technews.example.com/articles/8,Sam Wilson,2417.0
11,ART0012,Cloudflare Raises Series D Funding Round,Cloudflare,12/26/2022,Cloud Computing,NaN,Community contribution aims to accelerate inno...,https://technews.example.com/articles/12,NaN,1776.0
17,ART0018,Tesla CEO Discusses Future of AI,Tesla,04/30/2020,Big Data,NaN,New product features leverage cutting-edge AI ...,https://technews.example.com/articles/18,Jane Doe,739.0
...,...,...,...,...,...,...,...,...,...,...
705,ART0706,Databricks CEO Discusses Future of AI,Databricks,02-01-2024,Data Analytics,NaN,Financial results exceed analyst expectations ...,https://technews.example.com/articles/706,Jane Doe,1843.0
714,ART0715,Cohere Faces Regulatory Scrutiny,Cohere,06/26/2024,Cloud Services,NaN,Major partnership validates technology and ope...,https://technews.example.com/articles/715,NaN,1857.0
720,ART0721,Meta AI Launches New AI-Powered Product,Meta AI,2024-04-04,FinTech,NaN,Community contribution aims to accelerate inno...,https://technews.example.com/articles/721,NaN,2346.0
722,ART0723,Amazon Web Services Partners with Major Enterp...,Amazon Web Services,06-08-2024,Big Data,NaN,Major partnership validates technology and ope...,https://technews.example.com/articles/723,NaN,890.0
738,ART0739,xAI Releases Open Source Framework,xAI,"September 04, 2024",Software,NaN,Major partnership validates technology and ope...,https://technews.example.com/articles/739,Alex Johnson,1521.0

In [59]:
articles_df.groupby("company_name").count()[["revenue"]]

                             revenue
company_name
AWS                                2
Airbnb                            20
Amazon Web Services               27
Amazon Web Services (AWS)          2
Anthropic                         32
Azure                              3
CloudFlare                         3
Cloudflare                        29
Cohere                             7
Confluent                         35
Data Robot                         3
DataRobot                         26
Databricks                        22
Databricks Inc.                    3
DeepMind                           3
Elastic                           28
Facebook AI Research               3
Google DeepMind                   24
Google Deepmind                    2
Hugging Face                       2
Meta AI                           22
Meta AI Research                   3
Microsoft                         25
Microsoft Azure                    3
Mistral AI                         5
Mongo DB                           3
MongoDB                           31
NVIDIA                            25
NVIDIA Corporation                 3
Nvidia                             3
Open AI                            3
OpenAI                            21
OpenAI Inc.                        3
Palantir                          29
Palantir Technologies              3
Perplexity AI                      3
Scale AI                          34
Snowflake                         25
Snowflake Inc.                     3
SpaceX                            27
Stripe                            29
Stripe Inc.                        3
Tesla                             29
The Boring Company / SpaceX        3
Uber                              25
xAI                                4

In [61]:
articles_df.groupby("revenue").count()[["article_id"]]

                article_id
revenue
$0.045 billion           1
$0.095 billion           1
$0.120 billion           1
$0.135B                  1
$0.160 billion           1
...                    ...
€781,818,182             1
€795,454,545             1
€86,363,636              3
€954,545,455             1
€981,818,182             1

[487 rows x 1 columns]

In [37]:
companies_df.sort_values("company_name")

,company_name,founded_year,headquarters,employee_count,industry,is_public,stock_ticker
11,Airbnb,1999,"London, UK",19967,Data Analytics,False,NaN
5,Amazon Web Services,2015,"Berlin, Germany",27826,SaaS,False,NaN
1,Anthropic,2006,"San Francisco, CA",43747,FinTech,False,NaN
15,Cloudflare,1998,"Austin, TX",4422,Cybersecurity,False,CLOU
18,Confluent,1995,"London, UK",3884,Cloud Computing,False,NaN
19,DataRobot,2012,"New York, NY",23471,Cloud Computing,True,NaN
8,Databricks,2003,"Berlin, Germany",17962,Data Analytics,True,DATA
17,Elastic,2016,"San Francisco, CA",24508,Cybersecurity,True,ELAS
2,Google DeepMind,2017,"Austin, TX",24274,Data Analytics,False,NaN
3,Meta AI,2001,"Seattle, WA",20240,Data Analytics,True,NaN
4,Microsoft,2018,"Austin, TX",48646,Data Analytics,False,NaN
16,MongoDB,2008,"Austin, TX",16952,SaaS,False,MONG
7,NVIDIA,2017,"London, UK",22031,AI/ML,False,NaN
0,OpenAI,2006,"Austin, TX",12793,Data Analytics,False,OPEN
14,Palantir,2005,"Berlin, Germany",42306,Cloud Computing,True,NaN
20,Scale AI,2003,"Berlin, Germany",23379,AI/ML,False,NaN
9,Snowflake,2012,"London, UK",49545,Cloud Computing,True,NaN
13,SpaceX,2016,"Berlin, Germany",31018,AI/ML,False,NaN
10,Stripe,2002,"Seattle, WA",36348,Data Analytics,True,STRI
6,Tesla,2008,"London, UK",5691,Cloud Computing,True,NaN
12,Uber,2015,"San Francisco, CA",10144,FinTech,False,UBER

In [65]:
import re
import math


EUR_TO_USD = 1.10
GBP_TO_USD = 1.27
JPY_TO_USD = 1 / 150


def parse_arr_usd(value):
    """
    Parse a messy ARR/revenue string and return its value in USD as an integer.

    Returns None for missing, invalid, or undisclosed values.
    """

    # ---------------------------------------------------------
    # 1. Handle null / missing values
    # ---------------------------------------------------------
    if value is None:
        return None

    text = str(value).strip()

    if not text:
        return None

    missing_values = {
        "n/a",
        "na",
        "nan",
        "none",
        "null",
        "not disclosed",
        "undisclosed",
        "missing",
        "",
    }

    if text.lower() in missing_values:
        return None

    # ---------------------------------------------------------
    # 2. Detect currency
    # ---------------------------------------------------------
    text_upper = text.upper()

    if "€" in text or "EUR" in text_upper:
        conversion_rate = EUR_TO_USD

    elif "£" in text or "GBP" in text_upper:
        conversion_rate = GBP_TO_USD

    elif "¥" in text or "JPY" in text_upper:
        conversion_rate = JPY_TO_USD

    else:
        conversion_rate = 1.0

    # ---------------------------------------------------------
    # 3. Remove currency identifiers
    # ---------------------------------------------------------
    cleaned = text_upper

    for token in ["USD", "EUR", "GBP", "JPY", "$", "€", "£", "¥"]:
        cleaned = cleaned.replace(token, "")

    cleaned = cleaned.strip()

    # ---------------------------------------------------------
    # 4. Parse ranges
    # ---------------------------------------------------------
    range_parts = re.split(r"\s*[-–—]\s*", cleaned)

    if len(range_parts) == 2:
        first_value = _parse_numeric_amount(range_parts[0])
        second_value = _parse_numeric_amount(range_parts[1])

        if first_value is None or second_value is None:
            return None

        midpoint = (first_value + second_value) / 2
        usd_value = midpoint * conversion_rate

    else:
        # -----------------------------------------------------
        # 5. Parse single amount
        # -----------------------------------------------------
        parsed_value = _parse_numeric_amount(cleaned)

        if parsed_value is None:
            return None

        usd_value = parsed_value * conversion_rate

    # ---------------------------------------------------------
    # 6. Protect against NaN / inf
    # ---------------------------------------------------------
    if not math.isfinite(usd_value):
        return None

    return int(round(usd_value))


def _parse_numeric_amount(text):
    """
    Parse values like:
        5.2B
        500M
        5.2 BILLION
        5,200,000,000
    """

    if text is None:
        return None

    text = str(text).strip().upper()

    if not text or text in {"NAN", "NULL", "NONE", "N/A", "NA"}:
        return None

    text = text.replace(",", "")

    multiplier = 1

    if re.search(r"\bBILLION\b", text):
        multiplier = 1_000_000_000
        text = re.sub(r"\bBILLION\b", "", text)

    elif re.search(r"\bMILLION\b", text):
        multiplier = 1_000_000
        text = re.sub(r"\bMILLION\b", "", text)

    elif text.endswith("B"):
        multiplier = 1_000_000_000
        text = text[:-1]

    elif text.endswith("M"):
        multiplier = 1_000_000
        text = text[:-1]

    text = text.strip()

    try:
        numeric_value = float(text)
    except ValueError:
        return None

    if not math.isfinite(numeric_value):
        return None

    return numeric_value * multiplier

In [66]:
articles_df["arr_usd"] = articles_df["revenue"].apply(parse_arr_usd)

In [74]:
articles_df["arr_usd"].unique()[:30]

array([           nan, 3.10000000e+08, 9.80000000e+08, 1.68000000e+10,
       7.50000000e+10, 1.48000000e+09, 1.38000000e+09, 3.20000000e+08,
       3.20000000e+10, 2.60000000e+08, 2.52000000e+10, 1.03000000e+09,
       3.90000000e+09, 7.90000000e+08, 3.79999999e+08, 2.40000000e+09,
       1.70000000e+08, 9.30000000e+08, 2.15000000e+09, 1.26000000e+10,
       4.05000000e+10, 1.20000000e+09, 5.00000000e+09, 2.75000000e+08,
       6.20000000e+08, 6.10000000e+10, 7.60000000e+09, 3.05000000e+08,
       4.55000000e+08, 6.00000000e+08])

In [90]:
import pandas as pd
from datetime import datetime


def parse_published_date(value, ambiguous_day_first=False):
    """
    Parse a messy published_date value into a timezone-naive pandas Timestamp.

    Parameters
    ----------
    value : Any
        Raw date value from the source dataset.

    ambiguous_day_first : bool, default False
        Controls how ambiguous numeric dates are interpreted.

        False:
            06/09/2024 -> June 9, 2024

        True:
            06/09/2024 -> September 6, 2024

    Returns
    -------
    pandas.Timestamp | pd.NaT
        Parsed timezone-naive timestamp or pd.NaT when invalid/missing.
    """

    # ---------------------------------------------------------
    # 1. Handle missing values
    # ---------------------------------------------------------
    if value is None:
        return pd.NaT

    text = str(value).strip()

    missing_values = {
        "",
        "nan",
        "na",
        "n/a",
        "none",
        "null",
        "missing",
        "not available",
    }

    if text.lower() in missing_values:
        return pd.NaT

    # ---------------------------------------------------------
    # 2. Try known explicit formats first
    # ---------------------------------------------------------
    known_formats = [
        "%Y-%m-%d",      # 2024-09-06
        "%Y/%m/%d",      # 2024/09/06
        "%Y.%m.%d",      # 2024.09.06

        "%B %d, %Y",     # September 6, 2024
        "%b %d, %Y",     # Sep 6, 2024

        "%d %B %Y",      # 6 September 2024
        "%d %b %Y",      # 6 Sep 2024
    ]

    for fmt in known_formats:
        try:
            parsed_date = datetime.strptime(text, fmt)

            return pd.Timestamp(parsed_date)

        except ValueError:
            pass

    # ---------------------------------------------------------
    # 3. Fallback for numeric/mixed formats
    # Normalize timezone first, then remove timezone information
    # ---------------------------------------------------------
    try:
        parsed_date = pd.to_datetime(
            text,
            errors="raise",
            dayfirst=ambiguous_day_first,
            utc=True
        )

        # Convert:
        # Timestamp('2021-09-11 00:00:00+0000', tz='UTC')
        #
        # into:
        # Timestamp('2021-09-11 00:00:00')
        return parsed_date.tz_localize(None)

    except (ValueError, TypeError):
        return pd.NaT

In [91]:
articles_df["published_date_clean"] = (
    articles_df["published_date"]
    .apply(parse_published_date)
)

/tmp/ipykernel_273261/3397658558.py:80: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  parsed_date = pd.to_datetime(

In [92]:
articles_df[
    ["published_date", "published_date_clean"]
].head(30)

articles_df["published_date_clean"].unique()[:30]

<DatetimeArray>
['2020-02-21 00:00:00', '2023-02-23 00:00:00', '2022-02-17 00:00:00',
 '2023-12-13 00:00:00', '2021-12-28 00:00:00', '2021-10-26 00:00:00',
 '2022-10-19 00:00:00', '2022-10-07 00:00:00', '2023-02-07 00:00:00',
 '2022-11-05 00:00:00', '2021-10-25 00:00:00', '2022-12-26 00:00:00',
 '2023-08-23 00:00:00', '2020-01-15 00:00:00', '2020-09-27 00:00:00',
 '2020-04-20 00:00:00', '2021-07-24 00:00:00', '2020-04-30 00:00:00',
 '2023-01-15 00:00:00', '2023-10-14 00:00:00', '2023-10-03 00:00:00',
 '2020-07-23 00:00:00', '2021-09-11 00:00:00', '2023-05-23 00:00:00',
 '2020-09-24 00:00:00', '2023-04-07 00:00:00', '2022-04-12 00:00:00',
 '2020-11-22 00:00:00', '2023-09-13 00:00:00', '2020-08-24 00:00:00']
Length: 30, dtype: datetime64[us]

In [112]:
import re


CATEGORY_MAPPING = {
    "ai/ml": "AI_ML",
    "ai & ml": "AI_ML",
    "ai and ml": "AI_ML",
    "artificial intelligence": "AI_ML",
    "machine learning": "AI_ML",
    "ai": "AI_ML",
    "ml": "AI_ML",

    "cloud": "CLOUD",
    "cloud computing": "CLOUD",

    "data analytics": "DATA_ANALYTICS",
    "analytics": "DATA_ANALYTICS",

    "cybersecurity": "CYBERSECURITY",
    "cyber security": "CYBERSECURITY",

    "fintech": "FINTECH",
    "financial technology": "FINTECH",

    "saas": "SAAS",
    "software as a service": "SAAS",
}


def normalize_category(value):
    """
    Normalize messy article category values into a consistent taxonomy.

    Returns
    -------
    str | None
        Standardized category value, or None for missing values.
    """

    # ---------------------------------------------------------
    # 1. Handle missing values
    # ---------------------------------------------------------
    if value is None:
        return None

    text = str(value).strip()

    missing_values = {
        "",
        "nan",
        "na",
        "n/a",
        "none",
        "null",
        "missing",
    }

    if text.lower() in missing_values:
        return None

    # ---------------------------------------------------------
    # 2. Normalize formatting
    # ---------------------------------------------------------
    normalized_text = text.lower()

    normalized_text = normalized_text.replace("&", "and")

    # Collapse multiple spaces
    normalized_text = re.sub(r"\s+", " ", normalized_text)

    # Remove leading/trailing spaces
    normalized_text = normalized_text.strip()

    # ---------------------------------------------------------
    # 3. Apply explicit mapping
    # ---------------------------------------------------------
    if normalized_text in CATEGORY_MAPPING:
        return CATEGORY_MAPPING[normalized_text]

    # ---------------------------------------------------------
    # 4. Keep unknown categories instead of silently dropping
    # ---------------------------------------------------------
    return normalized_text.upper().replace(" ", "_")

In [113]:
articles_df["category_clean"] = (
    articles_df["category"]
    .apply(normalize_category)
)

In [108]:
normalize_category("AI & ML")

'AI_ML'

In [114]:
articles_df[
    ["category", "category_clean"]
].drop_duplicates().sort_values("category")

                   category       category_clean
8                   AI & ML                AI_ML
10                    AI/ML                AI_ML
2                 Analytics       DATA_ANALYTICS
3   Artificial Intelligence                AI_ML
17                 Big Data             BIG_DATA
29                    Cloud                CLOUD
11          Cloud Computing                CLOUD
44           Cloud Services       CLOUD_SERVICES
47            Cybersecurity        CYBERSECURITY
18           Data Analytics       DATA_ANALYTICS
14      Enterprise Software  ENTERPRISE_SOFTWARE
5                   FinTech              FINTECH
9                   Finance              FINANCE
0      Financial Technology              FINTECH
34                  InfoSec              INFOSEC
43         Machine Learning                AI_ML
22                     SaaS                 SAAS
6                  Security             SECURITY
1                  Software             SOFTWARE

In [111]:
import re
from difflib import SequenceMatcher


COMPANY_ALIASES = {
    "aws": "Amazon Web Services",
    "amazon web services aws": "Amazon Web Services",

    "open ai": "OpenAI",
    "openai inc": "OpenAI",

    "nvidia corporation": "NVIDIA",
    "nvidia corp": "NVIDIA",

    "databricks inc": "Databricks",

    "snowflake inc": "Snowflake",

    "mongodb inc": "MongoDB",

    "meta ai research": "Meta AI",
}


def _normalize_company_name(value):
    """
    Normalize a company name for comparison only.

    This does NOT become the final company name.
    """

    if value is None:
        return None

    text = str(value).strip().lower()

    missing_values = {
        "",
        "nan",
        "na",
        "n/a",
        "none",
        "null",
        "missing",
    }

    if text in missing_values:
        return None

    # Replace "&" consistently
    text = text.replace("&", "and")

    # Remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # Collapse multiple spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [122]:
def resolve_company_name(
    value,
    canonical_companies,
    fuzzy_threshold=0.90
):
    """
    Resolve a source company name to a canonical company name.

    Matching order:
        1. Exact normalized match
        2. Explicit alias mapping
        3. Conservative fuzzy matching

    Parameters
    ----------
    value : str
        Raw company name from the article dataset.

    canonical_companies : iterable
        Canonical company names from the metadata dataset.

    fuzzy_threshold : float, default 0.90
        Minimum similarity required for fuzzy matching.

    Returns
    -------
    str | None
        Canonical company name, or None if no reliable match exists.
    """

    normalized_value = _normalize_company_name(value)

    if normalized_value is None:
        return None

    # ---------------------------------------------------------
    # 1. Build normalized lookup from metadata
    # ---------------------------------------------------------
    canonical_lookup = {
        _normalize_company_name(company): company
        for company in canonical_companies
    }

    # ---------------------------------------------------------
    # 2. Exact normalized match
    # ---------------------------------------------------------
    if normalized_value in canonical_lookup:
        return canonical_lookup[normalized_value]

    # ---------------------------------------------------------
    # 3. Explicit aliases
    # ---------------------------------------------------------
    if normalized_value in COMPANY_ALIASES:
        alias_target = COMPANY_ALIASES[normalized_value]

        # Validate that alias target actually exists in metadata
        if alias_target in canonical_companies:
            return alias_target

    # ---------------------------------------------------------
    # 4. Fuzzy match
    # ---------------------------------------------------------
    best_match = None
    best_score = 0

    for normalized_canonical, canonical_name in canonical_lookup.items():

        score = SequenceMatcher(
            None,
            normalized_value,
            normalized_canonical
        ).ratio()

        if score > best_score:
            best_score = score
            best_match = canonical_name

    if best_score >= fuzzy_threshold:
        return best_match

    # ---------------------------------------------------------
    # 5. Unresolved
    # ---------------------------------------------------------
    return None

In [123]:
canonical_companies = companies_df["company_name"].tolist()

In [128]:
articles_df["company_name_resolved"] = (
    articles_df["company_name"]
    .apply(
        lambda x: resolve_company_name(
            x,
            canonical_companies
        )
    )
)

In [133]:
company_matches = (
    articles_df[
        ["company_name", "company_name_resolved"]
    ]
    .drop_duplicates()
    .sort_values("company_name")
)

company_matches

                    company_name company_name_resolved
502                          AWS   Amazon Web Services
26                        Airbnb                Airbnb
4            Amazon Web Services   Amazon Web Services
512    Amazon Web Services (AWS)   Amazon Web Services
25                     Anthropic             Anthropic
521                        Azure                   NaN
562                   CloudFlare            Cloudflare
11                    Cloudflare            Cloudflare
517                       Cohere                   NaN
3                      Confluent             Confluent
565                   Data Robot             DataRobot
1                      DataRobot             DataRobot
20                    Databricks            Databricks
560              Databricks Inc.            Databricks
522                     DeepMind                   NaN
22                       Elastic               Elastic
542         Facebook AI Research                   NaN
72               Google DeepMind       Google DeepMind
537              Google Deepmind       Google DeepMind
623                 Hugging Face                   NaN
2                        Meta AI               Meta AI
540             Meta AI Research               Meta AI
7                      Microsoft             Microsoft
520              Microsoft Azure                   NaN
501                   Mistral AI                   NaN
566                     Mongo DB               MongoDB
8                        MongoDB               MongoDB
5                         NVIDIA                NVIDIA
547           NVIDIA Corporation                NVIDIA
545                       Nvidia                NVIDIA
548                      Open AI                OpenAI
10                        OpenAI                OpenAI
556                  OpenAI Inc.                OpenAI
15                      Palantir              Palantir
574        Palantir Technologies                   NaN
516                Perplexity AI                   NaN
0                       Scale AI              Scale AI
60                     Snowflake             Snowflake
561               Snowflake Inc.             Snowflake
16                        SpaceX                SpaceX
29                        Stripe                Stripe
591                  Stripe Inc.                   NaN
6                          Tesla                 Tesla
588  The Boring Company / SpaceX                   NaN
12                          Uber                  Uber
544                          xAI                   NaN

In [134]:
def derive_company_size(employee_count):
    """
    Derive company size category from employee count.

    Rules:
        Small  -> fewer than 10,000 employees
        Medium -> 10,000 through 30,000 employees
        Large  -> more than 30,000 employees

    Returns
    -------
    str | None
        SMALL, MEDIUM, LARGE, or None for missing/invalid values.
    """

    if employee_count is None:
        return None

    text = str(employee_count).strip()

    missing_values = {
        "",
        "nan",
        "na",
        "n/a",
        "none",
        "null",
        "missing",
    }

    if text.lower() in missing_values:
        return None

    try:
        count = int(float(text))
    except (ValueError, TypeError):
        return None

    if count < 0:
        return None

    if count < 10_000:
        return "SMALL"

    elif count <= 30_000:
        return "MEDIUM"

    else:
        return "LARGE"

In [135]:
companies_df["company_size_category"] = (
    companies_df["employee_count"]
    .apply(derive_company_size)
)

In [117]:
companies_df[
    ["company_name", "employee_count", "company_size_category"]
]

           company_name employee_count company_size_category
0                OpenAI          12793                MEDIUM
1             Anthropic          43747                 LARGE
2       Google DeepMind          24274                MEDIUM
3               Meta AI          20240                MEDIUM
4             Microsoft          48646                 LARGE
5   Amazon Web Services          27826                MEDIUM
6                 Tesla           5691                 SMALL
7                NVIDIA          22031                MEDIUM
8            Databricks          17962                MEDIUM
9             Snowflake          49545                 LARGE
10               Stripe          36348                 LARGE
11               Airbnb          19967                MEDIUM
12                 Uber          10144                MEDIUM
13               SpaceX          31018                 LARGE
14             Palantir          42306                 LARGE
15           Cloudflare           4422                 SMALL
16              MongoDB          16952                MEDIUM
17              Elastic          24508                MEDIUM
18            Confluent           3884                 SMALL
19            DataRobot          23471                MEDIUM
20             Scale AI          23379                MEDIUM

In [136]:
import pandas as pd


def derive_company_age(founded_year, published_date):
    """
    Calculate company age as of the article published date.

    Parameters
    ----------
    founded_year : int | str
        Company founding year.

    published_date : pandas.Timestamp | datetime | str
        Cleaned article publication date.

    Returns
    -------
    int | None
        Company age in years, or None if inputs are missing/invalid.
    """

    # Handle missing founded year
    if founded_year is None:
        return None

    founded_text = str(founded_year).strip().lower()

    if founded_text in {
        "",
        "nan",
        "na",
        "n/a",
        "none",
        "null",
        "missing",
    }:
        return None

    try:
        founded_year = int(float(founded_year))
    except (ValueError, TypeError):
        return None

    # Handle missing / invalid published date
    if published_date is None or pd.isna(published_date):
        return None

    try:
        published_date = pd.Timestamp(published_date)
    except (ValueError, TypeError):
        return None

    company_age = published_date.year - founded_year

    # Prevent logically invalid negative ages
    if company_age < 0:
        return None

    return company_age

In [139]:
articles_enriched_df = articles_df.merge(
    companies_df,
    left_on="company_name_resolved",
    right_on="company_name",
    how="left"
)

In [140]:
articles_enriched_df["company_age"] = articles_enriched_df.apply(
    lambda row: derive_company_age(
        row["founded_year"],
        row["published_date_clean"]
    ),
    axis=1
)

In [141]:
articles_enriched_df[
    [
        "company_name_resolved",
        "founded_year",
        "published_date_clean",
        "company_age"
    ]
].head(20)

   company_name_resolved founded_year published_date_clean  company_age
0               Scale AI         2003           2020-02-21         17.0
1              DataRobot         2012           2023-02-23         11.0
2                Meta AI         2001           2022-02-17         21.0
3              Confluent         1995           2023-12-13         28.0
4    Amazon Web Services         2015           2021-12-28          6.0
5                 NVIDIA         2017           2021-10-26          4.0
6                  Tesla         2008           2022-10-19         14.0
7              Microsoft         2018           2022-10-07          4.0
8                MongoDB         2008           2023-02-07         15.0
9                MongoDB         2008           2022-11-05         14.0
10                OpenAI         2006           2021-10-25         15.0
11            Cloudflare         1998           2022-12-26         24.0
12                  Uber         2015           2023-08-23          8.0
13             Confluent         1995           2020-01-15         25.0
14                 Tesla         2008           2020-09-27         12.0
15              Palantir         2005           2020-04-20         15.0
16                SpaceX         2016           2021-07-24          5.0
17                 Tesla         2008           2020-04-30         12.0
18             Confluent         1995           2023-01-15         28.0
19             DataRobot         2012           2023-10-14         11.0